### ISSUE TITLE
JDK 11 Support

### ISSUE THREAD

**Issue by fborriello** [qubole/qds-sdk-java#106]
It would be useful to have a specific maven profile that builds the library with Java 11.
A possible command could be:
`mvn clean install -P jdk11-compliant`

**Comment by fborriello** [comment]
I've implemented it, see PR: [107](https://github.com/qubole/qds-sdk-java/pull/107)

**Comment by raunaqmorarka** [comment]
Merged fix on https://github.com/qubole/qds-sdk-java/pull/107 , thanks
