### ISSUE TITLE
The published javadocs are out of date

### ISSUE THREAD

**Issue by gubespam** [qubole/qds-sdk-java#116]
The [published docs](https://qubole.github.io/qds-sdk-java/apidocs/latest/com/qubole/qds/sdk/java/api/HiveMetadataApi.html) seem to have been generated from an older version which doesn't include the [table partitions API](https://github.com/qubole/qds-sdk-java/blob/master/src/main/java/com/qubole/qds/sdk/java/api/HiveMetadataApi.java#L68).

**Comment by gubespam** [comment]
Maybe the automation that updates the docs is broken?

**Comment by raunaqmorarka** [comment]
@gubespam Thanks for reporting the issue, I've published the latest docs from current code now.
