### ISSUE TITLE
Get command history by command type.

### ISSUE THREAD

**Issue by VenkataKarthikP** [qubole/qds-sdk-java#118]
Problem: 
client.command().history().invoke(); currently lists all commands from that user. But need to have ability to provide parameters for command type (say hive, presto...)

https://docs.qubole.com/en/latest/rest-api/command_api/view-command-history.html - Rest API already supports that - 
``` curl -i -X GET -H "X-AUTH-TOKEN:$AUTH_TOKEN" -H "Content-Type:application/json" -H "Accepts:application/json" \
-d '{"command_type":"ShellCommand,HiveCommand", "name":"named_command"}' \
"https://api.qubole.com/api/v1.2/commands" 
```

I feel we should have method to update parameters in https://github.com/qubole/qds-sdk-java/blob/master/src/main/java/com/qubole/qds/sdk/java/details/CommandApiImpl.java .

**Comment by raunaqmorarka** [comment]
Fixed with https://github.com/qubole/qds-sdk-java/pull/119
Thanks!
