### ISSUE TITLE
Maven artifacts missing

### ISSUE THREAD

**Issue by VenkataKarthikP** [qubole/qds-sdk-java#121]
Maven artifacts are missing for qds-sdk-java release 1.3.0 ( https://mvnrepository.com/artifact/com.qubole.qds-sdk-java/qds-sdk-java)

**Comment by ranganathhr** [comment]
@VenkataKarthikP Its now available in maven central repo https://mvnrepository.com/artifact/com.qubole.qds-sdk-java/qds-sdk-java/1.3.0
