### ISSUE TITLE
ResultStreamer not working with IAM roles

### ISSUE THREAD

**Issue by AdrianLa** [qubole/qds-sdk-java#66]
As an organization we recently moved to IAM roles over IAM keys.  We have now noticed that we cannot use the ResultStreamer to download large query results.  Looking at the code we noticed this snippet 
Account account = getAccount();
        AWSCredentials awsCredentials = new BasicAWSCredentials(account.getStorage_access_key(), account.getStorage_secret_key());
        final AmazonS3Client client = new AmazonS3Client(awsCredentials);
This does not work with IAM roles as we are not using keys.  We would like to continue to use the qds sdk rather than writing our own, is there a plan to remedy this issue?

**Comment by vogxn** [comment]
Would you like to raise a pull request? If not - we'll probably get to this sometime later this week or next.

cc @abhisheksr8

**Comment by abhisheksr8** [comment]
there is already a pr for this:
https://github.com/qubole/qds-sdk-java/pull/40/files

cc @guptavishal @amoghmargoor please review this and merge

**Comment by amoghmargoor** [comment]
@AdrianLa We have added support for ResultStreamer with IAM roles : https://github.com/qubole/qds-sdk-java/commit/c1ba1eb9dfa2673db45f93c2451cbbc69d4059d9

We will make a new SDK release soon.

**Comment by amoghmargoor** [comment]
@AdrianLa This issue should be resolved in new release 0.8.0. Closing this issue. Please feel free to reopen if you face any further problems with it. Thanks.
