### ISSUE TITLE
uploaded shaded 0.8.0 release to maven central

### ISSUE THREAD

**Issue by chpritchard-expedia** [qubole/qds-sdk-java#83]
Currently only the 0.7.0 jar was sent to maven central, from
https://github.com/qubole/qds-sdk-java/pull/45

**Comment by amoghmargoor** [comment]
Will make the release for the same.

**Comment by amoghmargoor** [comment]
@chpritchard-expedia We have made a new release 0.9.0 with the shaded jar. Will that work for you ?
